memtest86: Mark as broken
It fails with hardening-related errors like:

reloc.o: In function `.L41':
reloc.c:(.text+0x452): undefined reference to `__stack_chk_fail_local'

... and several others as well!

Since nobody has noticed that this package has been broken the entire
16.09 release, it's probably not worth to try fixing it.

(Note that this is a different package from memtest86plus!)