shutter: fix runtime error (missing imagemagick)
Fixes this:

  $ shutter
  ERROR: imagemagick is missing --> aborting!

Due to c3e95e324e22d4b121611cfd11a174d0c73fc918
("imagemagick: split dev output to fix #9604") which was committed in
the same period as shutter was added to nixpkgs.