ldns 1.6.17 -> 1.7.0 Release notes: http://git.nlnetlabs.nl/ldns/tree/Changelog?id=release-1.7.0
Openssl-1.1.0 is used to enable offline DANE verification (Needed for the DANE-TA usage type)

```
configure: error: OpenSSL does not support offline DANE verification (Needed for the DANE-TA usage type).  Please upgrade OpenSSL to version >= 1.1.0 or rerun with --disable-dane-verify or --disable-dane-ta-usage
builder /nix/store/m6n021fbk5h4iywzi3n26j95ksps9mwc-ldns-1.7.0. failed with exit code 1
error: build /nix/store/m6n021fbk5h4iywzi3n26j95ksps9mwc-ldns-1.7.0. failed
drvof drvfor
```