nixos/redis: fix evaluation
Commit f1ded4badfdca982d5f83b02c5dc0be9efff505b ("nixos/redis: clean up
option types") broke nixos evaluation:

  error: attempt to call something which is not a function but a set, at .../nixpkgs/nixos/modules/services/databases/redis.nix:111:28

Fix it.

Reported by Oliver Charles (thanks!).