kexec-tools: Add patch to fix build on ARM
Building on ARM fails with the following error:

kexec/arch/arm/phys_to_virt.o kexec/arch/arm/phys_to_virt.c
kexec/arch/arm/phys_to_virt.c:3:26: fatal error: phys_to_virt.h: No such file or directory

The patch I'm using is from Fedora:

http://pkgs.fedoraproject.org/cgit/rpms/kexec-tools.git/tree/kexec-tools-2.0.13-fix-armv7-build-failure.patch?id=97581f1a435aafa298a4d0bbcfaf40c63a41ce92

It has been reported upstream as well:

http://lists.infradead.org/pipermail/kexec/2016-September/017352.html

I'm adding the patch for all architectures, so that the next person to
upgrade kexec-tools doesn't forget that even while on x86.

Tested building with i686-linux, x86_64-linux and armv7l-linux.

Signed-off-by: aszlig <aszlig@redmoonstudios.org>