blender: unbreak cudaSupport
Currently it errors out at build time with:

/nix/store/HASH-cudatoolkit-6.5.19/usr_include/host_config.h:82:2:
  error: #error -- unsupported GNU version! gcc 4.9 and up are not supported!

Instead of downgrading gcc to 4.8, this patch upgrades cuda to 7.0, which
I think is the better choice. (Cuda 7 dropped support for some older graphics
cards, but gained support for newer ones.)