Intercal: a little fix
Intercal doesn't build with the most recent version of flex -
it complains with an "undefined reference to `yywrap'"
in the link phase.

So, we need to downgrade flex.