Revert "Revert "Explicitly pass -pthread flag to fix the build after some updates""
This reverts commit 5fb9a368a7c6f9c04e7cd242e2b382b2b9fb34a2.

I think the reason for the revert was because of patch dependencies. We really
need this patch to fix heimdal build.

Or else:

  $ nix-build -A heimdal
  ...
  /tmp/nix-build-heimdal-1.5.3.drv-0/heimdal-1.5.3/base/.libs/libheimbase.so: undefined reference to `pthread_getspecific'
  /tmp/nix-build-heimdal-1.5.3.drv-0/heimdal-1.5.3/base/.libs/libheimbase.so: undefined reference to `pthread_key_create'
  /tmp/nix-build-heimdal-1.5.3.drv-0/heimdal-1.5.3/base/.libs/libheimbase.so: undefined reference to `pthread_setspecific'
  collect2: error: ld returned 1 exit status
  Makefile:509: recipe for target 'tc' failed
  make[2]: *** [tc] Error 1