darwin.CoreOSMakefiles: remove
This wasn't being used and it was causing an error when evaluating:

error: attribute ‘CoreOSMakefiles’ missing, at /Users/mbauer/Projects/nixpkgs2/pkgs/os-specific/darwin/apple-source-releases/default.nix:140:71