pythonPackages.mutagen: 1.27 -> 1.32
(Not updating to the latest version, 1.34, because it breaks e.g.
'beets'. See https://github.com/beetbox/beets/issues/2153.)

The new version requires locale / i18n to be set-up for tests or else
this message is thrown:

  RuntimeError: This test suite needs a unicode locale encoding. Try setting LANG=C.UTF-8

Also, remove a test that currently fails due to the python builder in
nixpkgs. PR with fix: https://github.com/NixOS/nixpkgs/pull/17430
("python: add file encoding to run_setup.py").