ixgbevf: 4.0.3 -> 4.1.2
This fixes

  error: assertion failed at /home/eelco/Dev/nixpkgs-stable/pkgs/os-specific/linux/ixgbevf/default.nix:3:1
  (use ‘--show-trace’ to show detailed location information)

deploying a >=4.10 kernel to EC2. (We could probably also drop the
ixgbevf package with recent kernels, since the ixgbevf module included
in the kernel source tree is recent enough according to Amazon's
recommendation.)