Revert "nodePackages.yarn: remove package"
This reverts commit 0f7efe5acacc5049fc6ea404b92cb082f6d0d222.

Fixes:

    error: anonymous function at /home/travis/build/NixOS/nixpkgs/pkgs/development/node-packages/node-env.nix:3:1 called with unexpected argument ‘python’, at /home/travis/build/NixOS/nixpkgs/pkgs/development/node-packages/composition-v6.nix:8:13

This commit is doing a lot more than removing the yarn package, it also
upgrades a ton of other packages.