Fix eval
$ nix-env -f . -qa '*' --meta --xml --drv-path --show-trace
error: while querying the derivation named ‘python2.7-rpkg-1.50’:
attribute ‘gpl2plus’ missing, at .../pkgs/development/python-modules/rpkg/default.nix:24:15

Introduced by commit acbb79b9499aa0af499dd3857f8af016d3fc3b33
("rpkg: 1.14 -> 1.50").