beets-alternatives: Disable test suite for now
Regression introduced by 556f9b6b5186035b1f41887a0d9b4c85ab75cf90.

Running the tests results in the following traceback:
  ...
  File ".../unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File ".../test/regrtest.py", line 184, in <module>
    for module in sys.modules.itervalues():
RuntimeError: dictionary changed size during iteration

The reason for this is that the test directory itself is called "test"
and the package including regrtest.py is also called "test", so the
loader tries to load tests from its own implementation.

We could fix this by changing PYTHONPATH and/or making the test
directory a proper package, but we'd still have failing tests because
beets itself is required to run the tests.

However for now I'm just removing the unit_tests kwarg in setup.py so
that we have the same behaviour as before the initially mentioned
commit.

Signed-off-by: aszlig <aszlig@redmoonstudios.org>