go: fix build on Darwin
The go tests get tripped up due to error messages along the lines of:

    ld: warning: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation, ignoring unexpected dylib file

Which is due to us passing that along via $NIX_LDFLAGS in the `clang` wrapper.
To keep `go` from getting confused, I create a small `clang` wrapper that
filters out that warning.

Also, the strip.patch is no longer necessary, and only causes problems when
testing DWARF support:

    --- FAIL: TestDwarfAranges (0.59s)
        runtime-lldb_test.go:218: Missing aranges section
    FAIL
    FAIL    runtime 17.123s

Also, I disable the misc/cgo/errors test, as I suspect it is also due to similar
problems regarding `ld`:

    ##### ../misc/cgo/errors
    misc/cgo/errors/test.bash: BUG: expected error output to contain "err1.go:11:" but saw:
    # command-line-arguments
    cannot parse gcc output $WORK/command-line-arguments/_obj//_cgo_.o as ELF, Mach-O, PE object
    2016/05/07 02:07:58 Failed: exit status 1

Closes #14208