gradm: fix build on i686
This is a regression introduced by my update at 0817c91a3909728cb453e7f6f8dd3d729e731c1c

Turns out this was actually required to build the package on i686; without it,
the build fails with

```
/nix/store/[...]-flex-2.6.0/lib/libfl.so: undefined reference to `yylex'
```

for some reason ... the easiest solution is to just use flex_2_5_35, which does
build successfully.