Fix nixpkgs eval (caused by 'emscripten' expression)
Fixes this:

 $ nix-env -f . -qa '*' --meta --xml --drv-path --show-trace
 error: while evaluating ‘callPackageWith’ at .../lib/customisation.nix:93:35, called from .../pkgs/top-level/all-packages.nix:1411:24:
 while evaluating ‘makeOverridable’ at .../lib/customisation.nix:54:24, called from .../lib/customisation.nix:97:8:
 undefined variable ‘srcFC’ at .../pkgs/development/compilers/emscripten-fastcomp/default.nix:26:14

Also, "matthewbauer" is not defined in ./lib/maintainers.nix, comment
out.

Caused by 2b82ebb63038ffc296d9a97a66a4e9499b9b4a73 and
ee06fef48cc3c746b130cdb36c8590aa4b7c2d3b.